"""
Django settings for LibraryProject project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-1wl^urd4ivg4aydt)idy6!^rq!rvo6%)n=70kxhh&zk$a0o&z_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'relationship_app',  
    'users.apps.UsersConfig',
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'LibraryProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'LibraryProject.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# URL to redirect to after a user logs in
LOGIN_REDIRECT_URL = '/relationship/books/'  # Change this to your desired URL name or path
# URL to redirect to after a user logs out
LOGOUT_REDIRECT_URL = '/relationship/login/'   # Redirect back to the login page
AUTH_USER_MODEL = 'bookshelf.CustomUser'
# LibraryProject/settings.py

# --- Security Configuration ---

# 1. Set DEBUG to False in production for security. 
# This prevents displaying potentially sensitive configuration and tracebacks to users.
DEBUG = False

# Remember to define ALLOWED_HOSTS when DEBUG is False!
ALLOWED_HOSTS = ['yourdomain.com', '127.0.0.1', 'localhost'] 

# --- Cookie Security (Requires HTTPS) ---

# Enforce that the CSRF cookie is only sent over a secure (HTTPS) connection.
CSRF_COOKIE_SECURE = True
# Enforce that the session cookie is only sent over a secure (HTTPS) connection.
SESSION_COOKIE_SECURE = True
# Prevent client-side JavaScript from accessing the session cookie.
SESSION_COOKIE_HTTPONLY = True 

# --- Browser/Header Protections ---

# Prevents the browser from attempting to sniff the content type, 
# which can mitigate certain XSS risks.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Explicitly enable the browser's XSS filtering mechanism (though modern browsers 
# do this by default, it's good practice to set it).
SECURE_BROWSER_XSS_FILTER = True

# Protection against Clickjacking: 
# Denies permission to frame the page (recommended for most applications).
# Other options: 'SAMEORIGIN'
X_FRAME_OPTIONS = 'DENY'

# --- HSTS (HTTP Strict Transport Security) ---

# Tells the browser to only communicate with the site using HTTPS for the specified 
# duration (e.g., 31536000 seconds = 1 year). 
# Note: Requires HTTPS to be set up on your server.
SECURE_HSTS_SECONDS = 31536000  # Set to a high value like 1 year (31536000 seconds)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True # Optional, for HSTS preloading services

# --- Content Security Policy (CSP) Setup ---
# (Assuming you install and use the 'django-csp' package)
# Run: pip install django-csp
MIDDLEWARE = [
    # ... other middleware
    'django.middleware.security.SecurityMiddleware',
    # ... other middleware
    # Add CSP middleware near the top (after SecurityMiddleware)
    'csp.middleware.CspMiddleware',
    # ... other middleware
]

# Basic CSP configuration example (adjust for your needs)
# This policy is quite restrictive and helps prevent XSS by controlling resource loading.
CSP_DEFAULT_SRC = ("'self'",) 
CSP_SCRIPT_SRC = ("'self'", 'https://cdn.jsdelivr.net',) # Example: allow scripts from self and a CDN
CSP_STYLE_SRC = ("'self'", 'https://fonts.googleapis.com',) # Example: allow styles from self and Google Fonts
CSP_IMG_SRC = ("'self'", 'data:',) # Example: allow images from self and data URIs
CSP_FONT_SRC = ("'self'", 'https://fonts.gstatic.com',) # Example: allow fonts from self and Google Fonts
CSP_CONNECT_SRC = ("'self'",) 
CSP_OBJECT_SRC = ("'none'",) # Block plugins/objects

# ... rest of settings.py
# LibraryProject/settings.py
["SECURE_PROXY_SSL_HEADER", "HTTP_X_FORWARDED_PROTO"]
# --- Deployment & Security Pre-requisites ---

# Set to False in production. If True, Django will not redirect to HTTPS (Step 1).
DEBUG = False

# Must be set when DEBUG is False.
ALLOWED_HOSTS = ['yourdomain.com', '127.0.0.1', 'localhost']

# Ensure the SecurityMiddleware is included in the list
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',  # Crucial for security headers and redirects
    # ... other middleware
]

# --- Step 1: Configure Django for HTTPS Support ---

# SECURITY: Set to True to redirect all HTTP requests to HTTPS (301 Permanent Redirect).
# Requires HTTPS to be correctly configured on your web server.
SECURE_SSL_REDIRECT = True

# SECURITY: HTTP Strict Transport Security (HSTS)
# Instructs browsers that the site should ONLY be accessed using HTTPS 
# for the specified duration (e.g., 31536000 seconds = 1 year).
# This prevents man-in-the-middle attacks that downgrade connections to HTTP.
SECURE_HSTS_SECONDS = 31536000

# SECURITY: HSTS: Apply HSTS policy to all subdomains.
SECURE_HSTS_INCLUDE_SUBDOMAINS = True

# SECURITY: HSTS: Allows submission of the domain to browser HSTS preload lists.
SECURE_HSTS_PRELOAD = True

# SECURITY: By default, Django does not require a client certificate, 
# but this setting can be used to control the scheme detection for redirecting.
USE_X_FORWARDED_PROTO = True # Necessary if running behind a proxy (like Nginx/Apache)

# --- Step 2: Enforce Secure Cookies ---

# SECURITY: Ensures the session cookie is only sent by the browser over a 
# secure (HTTPS) connection.
SESSION_COOKIE_SECURE = True

# SECURITY: Ensures the CSRF cookie is only sent by the browser over a 
# secure (HTTPS) connection.
CSRF_COOKIE_SECURE = True

# SECURITY: Prevents client-side JavaScript from accessing the session cookie, 
# mitigating Cross-Site Scripting (XSS) risks related to session hijacking.
SESSION_COOKIE_HTTPONLY = True

# --- Step 3: Implement Secure Headers ---

# SECURITY: Clickjacking Protection
# Set to 'DENY' to prevent your site from being loaded in an iframe, 
# preventing clickjacking attacks.
X_FRAME_OPTIONS = 'DENY'

# SECURITY: MIME Type Sniffing Prevention
# Set to True to send the X-Content-Type-Options: nosniff header. 
# Prevents browsers from attempting to guess the content type of files, 
# which can mitigate certain XSS risks.
SECURE_CONTENT_TYPE_NOSNIFF = True

# SECURITY: Browser XSS Filter
# Set to True to send the X-XSS-Protection: 1; mode=block header. 
# This helps enable the built-in XSS filter in older browsers.
SECURE_BROWSER_XSS_FILTER = True
